
export-pdf:
	. .venv/bin/activate && python jobs/export_pdf.py --dsn "$(HP_DSN)"

validate-ndjson:
	. .venv/bin/activate && python jobs/validate_ndjson.py --file "$(FILE)"

import-ndjson:
	. .venv/bin/activate && python jobs/import_fhir_ndjson.py --file "$(FILE)" --dsn "$(HP_DSN)"
