name: Format & Lint

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install black ruff
      - name: Run black (check)
        run: |
          black --check .
      - name: Run ruff
        run: |
          ruff check .
